import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {children}
        {/* sizes on screen */}
      <span className="absolute bottom-0 left-0 ml-2 opacity-50 text-red-400">
        <span className="flex sm:hidden">-sm</span>
        <span className="hidden sm:flex md:hidden">sm</span>
        <span className="hidden md:flex lg:hidden">md</span>
        <span className="hidden lg:flex xl:hidden">lg</span>
      </span>
        </body>
    </html>
  );
}
