name: backend-tests

on:
  push:
    branches: [main, dev]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]

    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Set up Node.js ${{ matrix.node-version}}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version}}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        working-directory: ./src/backend

      - name: Run Tests
        run: pnpm test
        working-directory: ./src/backend
